# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a0413cac11fb96e84a0e2b1d8502e378e8bb6bce3a8cc7df55f38930573eec149a233d15bcb64f9f96f1c3dd7dccc9aefdc13052ee85a47cc3afa21cc0f8bda

test:
  secret_key_base: 80ac648c793b88a0468de9abba1eace46ca460dedad46363f239b13ff8fbb65b3565f0cb4b5ae9e4ebe665cfb9c1a17a41fc2966eaddf39d594a442810b904b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
